/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_urmet_ucontroller_HRBBus */

#ifndef _Included_cn_urmet_ucontroller_HRBBus
#define _Included_cn_urmet_ucontroller_HRBBus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_urmet_ucontroller_HRBBus
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_urmet_ucontroller_HRBBus_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     cn_urmet_ucontroller_HRBBus
 * Method:    test
 * Signature: (SIJFDCZBLjava/lang/String;Ljava/lang/Object;[I)V
 */
JNIEXPORT void JNICALL Java_cn_urmet_ucontroller_HRBBus_test
  (JNIEnv *, jobject, jshort, jint, jlong, jfloat, jdouble, jchar, jboolean, jbyte, jstring, jobject, jintArray);

/*
 * Class:     cn_urmet_ucontroller_HRBBus
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cn_urmet_ucontroller_HRBBus_init
  (JNIEnv *, jobject);

/*
 * Class:     cn_urmet_ucontroller_HRBBus
 * Method:    setNotifier
 * Signature: (Lcn/urmet/ucontroller/CanBusNotifier;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_urmet_ucontroller_HRBBus_setNotifier
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cn_urmet_ucontroller_HRBBus
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_urmet_ucontroller_HRBBus_uninit
  (JNIEnv *, jobject);

/*
 * Class:     cn_urmet_ucontroller_HRBBus
 * Method:    sendMsg
 * Signature: (ISBBB)I
 */
JNIEXPORT jint JNICALL Java_cn_urmet_ucontroller_HRBBus_sendMsg
  (JNIEnv *, jobject, jint, jshort, jbyte, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif
