/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_urmet_ucontroller_MsgNotifier */

#ifndef _Included_cn_urmet_ucontroller_MsgNotifier
#define _Included_cn_urmet_ucontroller_MsgNotifier
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
